### ISSUE TITLE
Replicate METviewer ROC diagram using Python

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/METplotpy#11]
## Describe the New Feature ##
Plot Receiver Operating Characteristic curve using a data array including thresholds, oy_i and on_y.  Example plot, xml, and data file included

![plot_20190904_141836](https://user-images.githubusercontent.com/23195803/64263705-562ef600-ceed-11e9-999b-8e9cf1a21d81.png)

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###

- [x] ~2 days reverse engineer R script roc.R in the METviewer repository
- [x] ~2 days create a default config file and two custom config files (in yaml)
- [x] ~1 day implement the Config class that handles reading in the config files
- [x] ~2-3 days implement the ROC class that generates the diagram
- [x] ~1-2 days implement customization of x-ticks in Python plotly (where support exists)
- [x] Add code to generate the .html file to support interactivity in METviewer
- [X] Incorporate changes from line plot (plotly) to support formatting of x-and y-axes
- [x] ~3 days GitHub Issue #85 incorrect plot generated in METviewer 
- [x] ~3 days GitHub Issue #81 Reverse connection order
- [x] ~ 3 days Add support for event equalization (replicate behavior in roc.R_tmpl in METviewer repository)
- [x] Add pytest tests
- [x]  Update README.rst documentation

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
June 2020 for alpha
end of July 2020 for beta

### Funding Source ###
2791541

### Assignee ###
- [x] Select Minna Win and Hank Fisher
- [x] Select Tara Jensen

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] (https://github.com/NCAR/METdb/issues/new/choose), [METviewer]
- [x](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress]
- [x] (https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy]

## New Feature Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
