### ISSUE TITLE
Generate Python version of the Taylor diagram

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#149]
## Describe the Enhancement ##
Reproduce the current METviewer functionality of the Taylor diagram, which is implemented in R

### Time Estimate ###
4 weeks

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
Split 2793541, 2788881, 2702691

### Assignee ###
- [ ] Select **engineer(s)** Minna Win
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by TatianaBurek** [comment]
@bikegeek , could you make this change :
import constants ->
import plots.constants as constants

I run the latest script version with UI and get the error:
```
File "/d3/projects/METViewer/METplotpy/metplotpy/plots/taylor_diagram/taylor_diagram_series.py", line 60, in _subset_data
subsetted_df = df_by_columns[df_by_columns['fcst_var'] == str(fcst_var_val[0])]
KeyError: 0
```
job # 20220204_133329

**Comment by bikegeek** [comment]
Made some changes to the default config file and the
taylor_diagram_series.py files.

It looks like pandas doesn't like the fcst_var_val[0] syntax when run
within METviewer, but is OK when run from the command line ( I don't know
why this works from the command line).  I hope I simplified the subsetting
by modifying the fcst_var_val_1 from a list to a single setting in the
config file, to remove the fcst_var_val[0] which *may* have been causing
the error???


---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by TatianaBurek** [comment]
could you make this change :
import constants ->
import plots.constants as constants
METviewer doesn't work with 'constants'

**Comment by TatianaBurek** [comment]
And now I am getting this error:
File "/d3/projects/METViewer/METplotpy/metplotpy/plots/taylor_diagram/taylor_diagram_series.py", line 92, in _create_series_points
fstdev_results = self.subsetted_df.query(fstdev_query)['stat_value'].values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by bikegeek** [comment]
It looks like METviewer is having issues with chained pandas commands.
Broke these up into separate commands.
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by TatianaBurek** [comment]
Here is the latest error:
`zero-size array to reduction operation minimum which has no identity`
No more specifics like the line number
