### ISSUE TITLE
Create line plot wrapper based on Mallory examples

### ISSUE THREAD

**Issue by fisherhucar** [dtcenter/METplotpy#17]
## Describe the New Feature ##
Create a wrapper to run the METplotpy histogram plot via METplus based on examples Mallory uses in METplus/parm/use_cases/plotting/examples

### Acceptance Testing ###
*List input data types and sources.*
Stat-analysis output provided by Mallory Row (NOAA EMC) located on host 'mohawk':
mohawk:/d2/projects/METplotpy/METplotpy_Issue#17:

- gfs_gfs_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead000000_fcstHGTP1000_obsHGTP1000_vxmaskNHX_dump_row.stat
- gfs_gfs_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead000000_fcstHGTP250_obsHGTP250_vxmaskNHX_dump_row.stat
- gfs_gfs_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead000000_fcstHGTP500_obsHGTP500_vxmaskNHX_dump_row.stat
- gfs_gfs_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead000000_fcstHGTP700_obsHGTP700_vxmaskNHX_dump_row.stat
- gfs_gfs_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead240000_fcstHGTP1000_obsHGTP1000_vxmaskNHX_dump_row.stat
- gfs_gfs_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead240000_fcstHGTP250_obsHGTP250_vxmaskNHX_dump_row.stat
- gfs_gfs_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead240000_fcstHGTP500_obsHGTP500_vxmaskNHX_dump_row.stat
- gfs_gfs_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead240000_fcstHGTP700_obsHGTP700_vxmaskNHX_dump_row.stat
- gfs_gfs_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead480000_fcstHGTP1000_obsHGTP1000_vxmaskNHX_dump_row.stat
- gfs_gfs_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead480000_fcstHGTP250_obsHGTP250_vxmaskNHX_dump_row.stat
- gfs_gfs_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead480000_fcstHGTP500_obsHGTP500_vxmaskNHX_dump_row.stat
- gfs_gfs_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead480000_fcstHGTP700_obsHGTP700_vxmaskNHX_dump_row.stat
- gfsv16_gfsv16_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead000000_fcstHGTP1000_obsHGTP1000_vxmaskNHX_dump_row.stat
- gfsv16_gfsv16_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead000000_fcstHGTP250_obsHGTP250_vxmaskNHX_dump_row.stat
- gfsv16_gfsv16_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead000000_fcstHGTP500_obsHGTP500_vxmaskNHX_dump_row.stat
- gfsv16_gfsv16_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead000000_fcstHGTP700_obsHGTP700_vxmaskNHX_dump_row.stat
- gfsv16_gfsv16_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead240000_fcstHGTP1000_obsHGTP1000_vxmaskNHX_dump_row.stat
- gfsv16_gfsv16_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead240000_fcstHGTP250_obsHGTP250_vxmaskNHX_dump_row.stat
- gfsv16_gfsv16_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead240000_fcstHGTP500_obsHGTP500_vxmaskNHX_dump_row.stat
- gfsv16_gfsv16_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead240000_fcstHGTP700_obsHGTP700_vxmaskNHX_dump_row.stat
- gfsv16_gfsv16_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead480000_fcstHGTP1000_obsHGTP1000_vxmaskNHX_dump_row.stat
- gfsv16_gfsv16_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead480000_fcstHGTP250_obsHGTP250_vxmaskNHX_dump_row.stat
- gfsv16_gfsv16_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead480000_fcstHGTP500_obsHGTP500_vxmaskNHX_dump_row.stat
- gfsv16_gfsv16_anl_valid20201121to20201221_valid0000to0000Z_init0000to0000Z_fcst_lead480000_fcstHGTP700_obsHGTP700_vxmaskNHX_dump_row.stat

*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2791541

### Assignee ###
- [x] Select **engineer(s)** Hank Fisher, Minna Win
- [x] Select **scientist(s)** Mallory Row
### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hankenstein2** [comment]
Current plan. We are going to use make_plots_wrapper as a conduit from METplus to plotting/METplotpy. Having a switch where users could use custom scripts straight from METplus or leverage METplotpy features both from make_plots_wrapper.
Our first plot/script to add to METplotpy is ush/plot_time_series.py that Mallory wrote. 
She is going to give us some sample StatAnalysis output stat files to work with.

**Comment by hankenstein2** [comment]
Mallory has indicated that they have other plots and this is not needed anymore
