### ISSUE TITLE
Create Plots for the Stratosphere Diagnostics

### ISSUE THREAD

**Issue by CPKalb** [dtcenter/METplotpy#170]
*Replace italics below with details for this issue.*

## Describe the New Feature ##
Examples of the needed plots are included below.  Note that we are using different data than what was used in those plots, so the output shouldn't match.  Specifically, the first plot is zonal mean wind (left) and temperature (right).  The lines are averages from the observations, and the contours are biases (as will be output from series_analysis).   The second is rmse and bias averaged between 60 and 90 degrees and over time.

### Acceptance Testing ###
Output from series_analysis will be added here when it is available

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2793541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by CPKalb** [comment]
![unnamed](https://user-images.githubusercontent.com/22180338/141513709-71139f85-244a-4ee3-b34b-9d9198831ec8.png)

**Comment by CPKalb** [comment]
![unnamed (1)](https://user-images.githubusercontent.com/22180338/141514015-d317cee4-a2f0-4e9e-84b3-0996ced6e732.png)

**Comment by CPKalb** [comment]
[pyzome_zonal-mean-example-data.pdf](https://github.com/dtcenter/METplotpy/files/7529577/pyzome_zonal-mean-example-data.pdf)
