### ISSUE TITLE
Make hovmoeller plot more configurable

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#213]
## Describe the Enhancement ##
The output from the hovmoeller diagram needs to be configurable, i.e. the user should be able to specify the path to the output directory in the configuration file.  The plot does not recognize the file path in the config file and saves the output in the directory from where the command is entered.

### Time Estimate ###
*Estimate the amount of work required here.*
~1 1/2 days 

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ]  Provide support for a custom config file to allow user to override the default config file
- [ ]  Remove hard-coded code that only uses the default config file
- [ ]  Replace the current command line arguments and put these in a custom config file

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** Minna Win
- [ ] Select **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose)
      - [ ] Make sure imports follow other plots to enable future incorporation into METplus use case 

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
Removed the command line options and moved these to the default and custom config file.  Created a hovmoeller_config.py file to handle the configuration settings.
