### ISSUE TITLE
Enhance the scatter plot to support marginal distributions and generalize the inputs and plotting options

### ISSUE THREAD

**Issue by TatianaBurek** [dtcenter/METplotpy#23]
*Enhance scatter plot*
![Screen Shot 2020-05-14 at 13 33 09](https://user-images.githubusercontent.com/21346768/81978068-34435280-95e8-11ea-9fd1-85f83ff63f83.png)
## Describe the New Feature ##
* This is an Idea from @JohnHalleyGotway:
Scatter plots from @willmayfield presentation show the histograms embedded along the x- and y-axes.  Would be nice to include this plot type in METplotpy.
We could plot FCST vs OBS columns from the MPR line type.  Or FBAR vs OBAR columns from the SL1L2 line type.  At least those would be 2 good examples.

Ooh, and the ability to color the dots by some other variable... such at HEIGHT?*

Make sure that the scatter plot functionality is added in as general a way as possible:
- Recommend turning on/off the marginal distributions an option.
- Enable the dots to be colored by some other metadata values.
   - Color by different model names (`MODEL`)
   - Color by different lead times (`FCST_LEAD`) or valid time (`FCST_VALID_BEG`)
   - Color by different masking regions (`VX_MASK`)
   - Color MPR data by their height value or lat/lon values

Some examples:
- Plot the `FCST` vs `OBS` data from the MPR line type.
- Plot the `FBAR` vs `OBAR` data from SL1L2 line type.
- Plot the `ME` of `TMP` vs the `ME` of `RH` from the CNT line type.
- Recommend that @anewman89 and @DanielAdriaansen add additional examples of useful scatter plot types.

Would also like this functionality to be added to METviewer in the future and would need a new METviewer issue to do so. When developing this plot type, do it with adding this new plot type to METviewer in mind.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2702701 NCAR Base

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
- [ ] Write a new issue to incorporate this new plot type in METviewer.

## New Feature Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
generated a reformatter in METdataio:

- https://github.com/dtcenter/METdataio/issues/255
- set up code to run/test on 'seneca': /d1/projects/Land_Visualization/reformat_mpr

**Comment by bikegeek** [comment]
- refactored the scatter plot from original plotly implementation to Matplotlib
- scatter plot can read MPR input to generate the FCST vs OBS plot, with points colored by value
- set up plotting code on 'seneca' using sample MPR data from the MET regression tests: /d1/projects/Land_Visualization/scatter_plot

**Comment by bikegeek** [comment]
need to verify whether to proceed with testing scatter plot with SL1L2 and CNT data within the confines of current funding.
