### ISSUE TITLE
Plot new TC-Diagnostics output from TC-Pairs

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METplotpy#233]
## Describe the New Feature ##

The key targets for plotting development in this issue are (from the [04/07/2023 project-wide meeting](https://docs.google.com/document/d/1KKTpn7VKDqg_bYVhBgMY8qfxoApNgkFsqYohnw6uHQ4/edit?usp=sharing)):
1. Display the distributions of diagnostics by storm, by season, by model 
2. Skew-Ts 
3. Time series of diagnostic values for forecasts

More details:
**1. Display the distributions of diagnostics by storm, by season, by model** 
- This will be useful for researchers and forecasters wanting to understand retrospective evaluation of model performance.
- E.g., shear vs. different models
- By default, the filtering is homogeneous.
- METplotpy has transitioned the Rscript codes to do boxplots based on errors, so it’s just a matter of switching these over from errors to diagnostics. 
- The new TCpairs line type is TCDiag which comes after MPR has paired values, not columns. Not trivial to adapt.
- This could also be conditioned by errors or thresholded diagnostic value (e.g., low shear).
 
**2. Skew-Ts** 
- This will be useful for forecasters - sanity check on model’s atmospheric structure, but also to check to see if there are aspects not captured by the standard diagnostics (e.g., mid-level jet, SAL inversion, etc.).
- These are area-averaged values, not a sounding at a point.
- In theory, the point soundings COULD be done from the cylindrical grid and compared to the large-scale. 
- But for now, focus on one sounding - the single values out of the diagnostics without regard to the area it has been averaged over (can be read directly from the ASCII or TC-Pairs, if included). 
- This low hanging fruit. Just plot the column of single numbers for each forecast hour.

**3. Time series of diagnostic values for forecasts**
- This is a real-time type of plot for forecasters
- Similar to what CIRA is producing. Representing what is in the current diagnostic file. 

More information:

- 1 and 3 would fit under the guise of the TC-MPR plotter (a doable modification). 
- 2 would probably be separate from TC-MPR plotter. Probably the most viable task to tackle first. 
- Start by using the diagnostic data from TC-pairs. 

This issue is related to:
- dtcenter/MET#2168 defines a new MET tool named TC-Diag.
- dtcenter/MET#392 enhances TC-Pairs to read the Tropical Cyclone Diagnostics output from TC-Diag (or other sources) and incorporate it into the output of the TC-Pairs tool.
- dtcenter/METdataio#87 loads the updated TC-Pairs output into a MET database.
- dtcenter/METdataio#240
- dtcenter/METplotpy#383 creates documentation and testing for TCMPR plotting code
- dtcenter/METplotpy#342 enhances TCMPR plotter to read TCDiag lines and filter by one column and plot another column

For now, this task will focus on developing python-based plotting in METplotpy. 

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*NOAA WPO - JTTI TCDiag Project (2770043)*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @bikegeek and @TatianaBurek 
- [x] Select **scientist(s)** or **no scientist** required: @KathrynNewman and @jvigh 

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] dtcenter/MET#2168
- [x] dtcenter/MET#392
- [x] dtcenter/METdataio#87
- [x] dtcenter/METdataio#240
- [x] dtcenter/METplotpy#383
- [x] dtcenter/METplotpy#342

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
Skew T's  issue: https://github.com/dtcenter/METplotpy/issues/339
code is available in feature_337_tcdiag_skewt (*note that the feature number should be 339 and not 337)

**Comment by bikegeek** [comment]
This is awaiting evaluation by Jonathan Vigh for the use case that uses this plot:
https://github.com/dtcenter/METplus/issues/2359

**Comment by bikegeek** [comment]
Reading in the TC Diag columns from TC Pairs output has been completed:
https://github.com/dtcenter/METdataio/issues/87

**Comment by bikegeek** [comment]
The TCMPR plotting for plotting the TC Diag columns was completed: https://github.com/dtcenter/METplotpy/issues/342

**Comment by bikegeek** [comment]
Reformatting TCDiag data has been completed:
https://github.com/dtcenter/METdataio/issues/240

**Comment by bikegeek** [comment]
All sub-tasks/issues that make up this issue have been completed.  Closing this issue.
