### ISSUE TITLE
Clean up release notes 

### ISSUE THREAD

**Issue by lisagoodrich** [dtcenter/METplotpy#273]
## Describe the Task ##
For continuity, all METplus products will have the Release Notes broken out into their own chapter.  This has already been done for METplotpy.  (Release Notes Chapter 24). https://metplotpy.readthedocs.io/en/develop/Users_Guide/release-notes.html. Normally it would be Chapter 2 but for now, it will stay where it was created.

Essentially, make it look like the [MET Release Notes](https://met.readthedocs.io/en/feature_2296_release_notes_move/Users_Guide/release-notes.html) for consistency (that link is to your feature branch, if that should be merged into develop before you do this work that link will no longer work, but this [link](https://met.readthedocs.io/en/develop/Users_Guide/release-notes.html) should.) by following the steps listed below, modifying header types as needed:

1. Change the title from "METplotpy 1.1.0 Release Notes" to be "METplotpy Release Information"
2. The current "24.1. Version 1.1.0 release notes (2022-09-14)" title will become "METplotpy Release Notes"
3. The current "24.1.1. Version 2.0.0 release notes (20220914)" will become "24.1.1 METplotpy Version 2.0.0-beta3 release notes (20220914)"
4. The current "24.1.2 beta3 release" section will be removed.
5. The current "24.1.3 beta2 release" will become "24.1.2 METplotpy Version 2.0.0-beta2 release notes (20220803)"
6. The current "24.1.4 beta1 release" will become "24.1.3 METplotpy Version 2.0.0-beta1 release notes (20220622)"
7. Create a new 24.2 section called "METplotpy Upgrade Instructions" (with paragraph text "Upgrade instructions will be listed here if they are applicable for this release.")

### Time Estimate ###
Less than 1 day of work.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*MET-11.0.0-beta4 release*

### Funding Source ###
2792541*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [x] Close this issue.

**Comment by jprestop** [comment]
@lisagoodrich I updated the link to the METplotpy release notes above.  It had been pointing to the "latest", but we wanted to use "develop" as a reference.  As a result, anything referencing Chapter 24 above now refers to Chapter 26.  I made those changes above and added some further detail.  Please let me know if you have any questions.  Thanks!
