### ISSUE TITLE
Create a figure directory

### ISSUE THREAD

**Issue by lisagoodrich** [dtcenter/METplotpy#293]
*Replace italics below with details for this issue.*

## Describe the Task ##
*The METplus Contributor's Guide has a "figures" folder for all the jpg & png and images for the documentation.  For the sake of continuity, create a "figures" folder under 
git/METplotpy/docs/Users_Guide/
to house the close to 50 png images that are currently in this directory.

* The paths to these directories will also need to be updated in the documentation

### Time Estimate ###
*Estimate the amount of work required here.*
*Under 3 days of work.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*
NONE

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*
NONE

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required. This work Lisa Goodrich should be able to complete.
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
