### ISSUE TITLE
Inconsistency in output plot name value in configuration file

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#30]
## Describe the Task ##
Earlier yaml config files (line, histogram, scatter, box) use 'image_name' for the keyword to indicate the output plot name but in the yaml config files created by METviewer for the performance diagram, plot_output is the keyword.  Make all the keynames the same, plot_filename.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.
~ 1-2 hours

### Sub-Issues ###
Replace image_name with plot_filename in the following config files:
- [x] Edit histogram_defaults.yml
- [x] Edit performance_diagram_default.yaml
- [x] Edit roc_diagram_defaults.yaml
- [x] Edit custom_performance_diagram.yaml
- [x] Edit custom_roc_diagram.yaml
- [x] Edit custom_scatter.yaml

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s) Minna Win
- [x] Select **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the task and verify your changes.
- [x] Push local changes to GitHub.
- [x] Close this issue.
