### ISSUE TITLE
Refactor CBL code to isolate plotting and replace Basemap with Cartopy

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#33]
Recreate (within roundoff errors) the figure provided by Tina that is currently created by the CBL.py code.  Replace using Basemap with Cartopy (as Basemap is deprecated and will NOT be supported in NOAA hosts).  

Example figure is below:
![Screen Shot 2020-08-25 at 3 06 32 PM](https://user-images.githubusercontent.com/3753118/91228638-d0035500-e6e5-11ea-836c-f632adedb12c.png)

NOTE: Differences between the two implementations are anticipated due to round off errors. The input data  used in the original script is not CF-compliant netCDF and the input that will be used for this plot is generated from grib data.  

Sample scripts are located on host 'eyewall', at /d1/block_S2S_METplotpy:

- CBL.py

- CBL.nc

- Figure_1.png

- Z500dayDJF.nc

## Describe the Task ##
Using the scripts and example input found on eyewall at: /d1/Blocking_S2S_METplotply, create a map plot for this step of the blocking sub-seasonal to seasonal use case. 
 
### Time Estimate ###
*Estimate the amount of work required here.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Modify CBL.py script by replacing Basemap with Cartopy (using Z500dayDJF.nc file supplied by Tina K.)
- [x] Modify CBL.py and create CBL_plot.py for plotting logic into CBL_plot.py 
- [x] Modify CBL.py and create CBL_compute.py for calculating the CBL (Central Blocking Latitude) 
- [X]  Incorporate into the METplus Blocking_driver.py script

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select Minna Win
- [x] Select Tina Kalb

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the task and verify your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
