### ISSUE TITLE
Determine if ordering of independent variable labels is correct in remaining plots

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#337]
## Describe the Task ##
From issue # 218, go through the remaining plots and ensure that independent labels ordering is maintained for threshold values.  This has been found in bar plots, investigate the remaining plots (used by METviewer) to ensure that the same fix is implemented.  For reference, please see:
(https://github.com/dtcenter/METplotpy/issues/218)

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*
1-3 days for each plot, based on obtaining or creating data, making the modifications, and testing the modifications.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
Affected plots:
- [ ] *Line plot*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** Minna Win
- [x] Select **scientist(s)**  No scientist

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
For box plot:
1) generated threshold data using METviewer and the mv_tatiana database:

- ACPC_12, BASER, BCMSE, FBAR, FAR
- MODEL, WRF
- OBS_THRESH, selected 
2) Updated the yaml file 
Box plot handles the OBS_THRESH indy_labels properly, no need to make modifications.

**Comment by bikegeek** [comment]
**Unaffected plots:**
mpr plot
performance diagram
ROC diagram
wind rose diagram
Taylor diagram
polar plot
mjo_rmm
mjo_enso
spacetime plots
stratosphere diagnostics
hovmoeller
tc-rmw

**Comment by bikegeek** [comment]
**Plots that already correctly handle obs_thresh data:**

bar plot
