### ISSUE TITLE
Create skew-T (sounding) plots from TC-Diag ASCII output

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#339]
## Describe the New Feature ##
Generate skew-T logP (soundings) plots, one for each day's TC Diag output (ASCII).  Design the plotting so that it supports running stand-alone and as part of a real-time work flow.

### Acceptance Testing ###
Data is located on 'seneca': /d1/projects/TCDiag/data_output/DIAGNOSTICS/TCDIAG/2022/al092022
more data will be forthcoming

*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.* 
*Issues should represent approximately 1 to 3 days of work.*
at least 3 days of iterative work and meetings to finalize the appearance and functionality of the plots.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [x] *Read the ASCII file and retrieve the necessary fields for generating a skew-T plot.*
- [x] *Create a configuration file to support customizing the appearance of the plot, to indicate the location of input and output, etc.*
- [ ] *Set up the plotting to support two different work flows: real-time generation and stand-alone*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*NOAA WPO - JTTI TCDiag Project (2770043)*

### Assignee ###
- [x] Select **engineer(s)** Minna Win
- [x] Select **scientist(s)** Kathryn Newman and Jonathan Vigh

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), METplus Use case will be created

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
