### ISSUE TITLE
Enhance TCMPR plotter to read TCDiag lines and filter by one column and plot another column

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#342]
## Describe the Enhancement ##
Add support to the TCMPR plotting code to read TCDiag lines.
Allow filtering by a specified column and plotting of another specified column.  Append these TCDiag lines to the TC MPR data.  

This work ties in with this use case:
https://github.com/NCAR/TCDiag-use-cases/issues/5
### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [x] *Read in the TCDiag line type into a pandas dataframe*
- [x] *Allow user to select one column of data and another column to plot via configuration file*
- [x] *Append the TCDiag lines to the TCMPR data. Refer to the MET documentation.  In Table 24.2 TCMPR, column 85 will be the DIAG_SOURCE from the TCDiag line type, column 86 will be the TRACK_SOURCE, etc.*
- [x] *Filter the TCDiag data by diagnostic values to stratify track and intensity errors by diagnostic value (such as shear).  Allow the user to specify this diagnostic in the configuration file.*

These will not be finished for this issue, moving them to this issue: https://github.com/dtcenter/METplotpy/issues/442
- [ ] *Allow user to specify threshold values in the config file, ie. when wind shear is >30 kts, plot the distribution of errors. 
- [ ] *Support any other filtering, customizing the plots by allowing coloring of points based on diagnostic type.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** Minna Win 
- [x] Select **scientist(s)** Jonathan Vigh & Kathryn Newman

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
Refer to this issue:
https://github.com/dtcenter/METplotpy/issues/233

**Comment by bikegeek** [comment]
created new issue to address the handling of thresholds and changing marker colors based on diagnostic type.  These are beyond the allotted time:

https://github.com/dtcenter/METplotpy/issues/442
