### ISSUE TITLE
Add GridDiag output plots.

### ISSUE THREAD

**Issue by davidfillmore** [dtcenter/METplotpy#36]
*Replace italics below with details for this issue.*

## Describe the New Feature ##
Add plot types for GridDiag histogram output.
The metplotpy type histogram_2d will be able to plot 2D histograms
from output files generated by GridDiag or other applications writing
histogram data in NetCDF format.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*
Regression test output from MET GridDiag will be the test input for this plot type.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*
4 days.

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
Split between 2785051, 2791541, 2799991, 2700041 - please make sure it only takes 4 days.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
David Fillmore
- [x] Select **scientist(s)** or **no scientist** required
Tracy

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by dwfncar** [comment]
Merged to develop.
