### ISSUE TITLE
Update documentation on plots that now support logging

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#368]
## Describe the Task ##
As a result of addressing the CATII and CATIII STIG issues, some METplotpy plots now have logging support.  

Update the User's Guide and necessary example config files to reflect the logging 

### Time Estimate ###
*Estimate the amount of work required here.*
1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*
Before coordinated release

### Funding Source ###
2792543

### Assignee ###
- [x] Select **engineer(s)** 
- [x] Select  **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
Files updated:

### Hovmoeller:

-  hovmoeller.rst
-  custom_hovmoeller.rst
-  hovmoeller_defaults.rst


### Bar:

- bar.rst
- custom_bar.yaml
- bar_defaults.yaml

### Box:

- box.rst
- custom_box.yaml
- box_defaults.yaml

### Contour:

- contour.rst
- custom_contour.yaml
- contour_defaults.yaml

### eclv (economic cost-loss value):

- eclv.rst
- eclv_defaults.yaml
- custom_eclv.yaml

### ens_ss:
- ens_ss.rst
- ens_ss_defaults.yaml
- custom_ens_ss.yaml


### equivalence_testing:
no user's documentation
- equivalence_testing_bounds_default.yaml

### histogram:
- hist_defaults.yaml
- histogram.rst
- prob_hist.yaml
- rank_hist.yaml
- rel_hist.yaml

### histogram_2d:

- histogram_2d_defaults.yaml
- custom_histogram_2d.yaml
- histogram_2d.rst


### Line:

- line_defaults.yaml
- line.rst
- custom_line.yaml

### mpr_plot:
no user documentation
- mpr_plot_defaults.yaml


### performance_diagram:
- performance_diagram_defaults.yaml
- performance_diagram.rst
- minimal_performance_diagram.yaml
- custom_performance_diagram.yaml

### reliability diagram:
- reliability_defaults.yaml
- custom_reliability_diagram.yaml
- reliability_diagram.rst

### revision_box:
no users guide documentation
revision_box_defaults.yaml

### revision_series:
no users guide documentation
revision_series_defaults.yaml

### roc_diagram:
- roc_diagram_defaults.yaml
- roc_diagram.rst
- custom_roc_diagram.yaml

### Taylor diagram:

- taylor_diagram_custom.yaml
- taylor_diagram.rst


### wind rose diagram:

- wind_rose_defaults.yaml
- wind_rose_custom.yaml
- wind_rose.rst
