### ISSUE TITLE
Update fv3_physics_tend for new FV3 output format

### ISSUE THREAD

**Issue by ahijevyc** [dtcenter/METplotpy#380]
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
Update contributed/fv3_physics_tend
Read and plot FV3 physics tendencies from new FV3 output format.  

### Time Estimate ###
*Estimate the amount of work required here.*
7 days

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [x] adapt planview_fv3.py for new formulation of no-physics (advection) tendency. Now it is reset every output just like the other tendencies. This simplifies the code. However, it can't simply be addressed in the config file.
- [x] adapt cross_section_vert.py for new nophys
- [x] adapt vert_profile_fv3.py for new nophys
- [x] add "actual" tendency panel to the multi-panel plan view plot
- [x] add --robust command line option to control colormap range to planview_fv3.py and cross_section_vert.py
- [x] fix bug in time-averaging window in planview, cross_section_vert, and vert_profile_fv3.
- [x] retain units on xarray xaxis in vert_profile_fv3.py
- [x] add vmin, vmax to planview and cross section
- [x] add xmin, xmax to vert_profile_fv3.py
- [x] clean code, leaving out unnecessary function arguments, use pep8 filter
- [x] update history file
- [x] update example plot output PNGs

### Relevant Deadlines ###
NONE
### Funding Source ###
NONE
### Assignee ###
- [x] Select **engineer**
- [x] Select **scientist**

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)** Gerard Ketefian - NOAA Affiliate <gerard.ketefian@noaa.gov> Sarah Womantree - NOAA Affiliate <sarah.womantree@noaa.gov>

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [x] Add/update documentation.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [x] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
