### ISSUE TITLE
Create documentation and testing for TCMPR plotting code 

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#383]
## Describe the Task ##
The Python version of the MET tcmpr plotter written in R is now finished but needs tests and documentation. 

- Please refer to the existing [plot_tcmpr.R](https://github.com/dtcenter/MET/blob/main_v11.1/scripts/Rscripts/plot_tcmpr.R) script this replaces.
- Review the usage statement to make sure sufficient equivalent configuration options are provided by this Python version.
- In particular, confirm that event equalization logic is provided and works as expected.
- Check whether the 8 plot types are supported (BOXPLOT, POINT, MEAN, MEDIAN, RELPERF, RANK, SKILL_MN, SKILL_MD) or coordinate with @KathrynNewman to confirm their removal.
- Add tests to cover a reasonable sample of the functionality.
- Provide a description of each supported plot type in the documentation, and perhaps an example. But mostly just make the documentation consistent with the existing level of detail for METplotpy.

### Time Estimate ###
Approximately 2-3 days for writing tests
Approximately 2 days for creating, verifying, and finalizing documentation

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] Document instructions for generating each plot type supported
- [ ] Create tests to verify that plots are getting generated and visually match what is expected (if image comparison is reliable)

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
Completed with PR: https://github.com/dtcenter/METplotpy/pull/441
