### ISSUE TITLE
Recreate plot generated in the blocking S2S script CALC_IBL.py

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#40]
Recreate plot generated in the blocking S2S script CALC_IBL.py

IBL = Instantaneously blocked latitude

![Screen Shot 2020-08-25 at 3 03 04 PM](https://user-images.githubusercontent.com/3753118/91227711-37200a00-e6e4-11ea-9e63-7c9d810a178b.png)

## Describe the Task ##
Generate line plots that were originally created by the CALC_IBL.py.  Implement using Matplotlib and make implementation importable for re-use by other code.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2785051

### Assignee ###
- [x] Select **engineer(s)** Minna Win
- [x] Select **scientist(s)** Tina Kalb

### Labels ###
- [X] Select **component(s)** 
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
