### ISSUE TITLE
Optimize plotting in the Physics Tendency planview, cross-section, and vertical cross-section plots

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#449]
*Replace italics below with details for this issue.*

## Describe the Enhancement ##
The interface for generating the physics tendency plots require numerous command line arguments that creates challenges in maintaining the accompanying METplus Use cases.  Replace the command line arguments with values in a configuration file.

The three METplus Use cases will need to be updated to reflect these changes. 

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as a **METplotpy-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [ ] For a **METplotpy-X.Y.Z** version, select the **METplotpy-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METplotpy-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by ahijevyc** [comment]
Hi @bikegeek (Minna), 

I started a branch `issue449_optimize_physics_tend_config` to move the optional command line arguments to the configuration file. I also moved `planview`, `cross_section_vert`, and `vert_profile` methods out of their respective `main` methods and into their own functions. That should make it easier to access them outside of the command line.

Now that the output filename, along with other variables, are defined in the configuration file, perhaps the test scripts can be cleaned up. For example, in `test/fv3_physics_tend/runner_planview.py` the functions `run_with_novel_output_file` and `run_with_novel_output_dir` may be removed?

**Comment by bikegeek** [comment]
I am under a deadline to get some other things finished, can this wait
until next week?

**Comment by bikegeek** [comment]
I took a look and the tests are running fine with the tests that invoke those functions.  I'm inclined to leave those in place in the event any future changes are made to the filenaming convention.

**Comment by ahijevyc** [comment]
There was one test file `runner_vert_profile.py` that might need editing. It has two functions named `run_example`.

**Comment by bikegeek** [comment]
If you don't see any changes to running the example, then go ahead.  Typically we don't like to remove tests to ensure that changes in what we think are unrelated will not affect existing code (regression testing)
