### ISSUE TITLE
Add Space-time Coherence Spectra from PSL Diagnostics package

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/METplotpy#46]
## Describe the New Feature ##
Related to the METplotpy issue: 
https://github.com/dtcenter/METplotpy/issues/46

and METcalcpy issue #29
https://github.com/dtcenter/METcalcpy/issues/29

Take existing scripts for creating a spacetime plot and incorporate them into the METplotpy repository under the METplotpy/metplotpy/contributed directory.  Utilize the code in METcalcpy/metcalcpy/contributed/spacetime to perform the necessary calculations for generating the plots.

### Acceptance Testing ###
Data (as netCDF) resides on 'kiowa', under the /d1/projects/METcalcpy/METcalcpy_Data/TropicalDiagnostics directory, 

Verify that various spacetime plots can be generated and that they are consistent with those generated by Maria Gehne/NOAA PSD:
![SpaceTimeCoherence_ERAIPD850](https://user-images.githubusercontent.com/1524012/114933918-7ecfdf00-9df6-11eb-912f-6826a1161958.png)

### Time Estimate ###
~1-2 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** Hank Fisher and Minna Win
- [x] Select **scientist(s)** Maria Gehne

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by dwfncar** [comment]
![SpaceTimeCoherence_ERAIPD850](https://user-images.githubusercontent.com/1524012/114933918-7ecfdf00-9df6-11eb-912f-6826a1161958.png)
Sample plot from Maria.

**Comment by hankenstein2** [comment]
Finished
