### ISSUE TITLE
Add a configurable option for importing CompareImages 

### ISSUE THREAD

**Issue by jprestop** [dtcenter/METplotpy#471]
## Describe the Enhancement ##
When running test/run_all_nco.sh or test/pythest on WCOSS2, the code errors out with:
```
ModuleNotFoundError: No module named 'imutils'
```
These failures were not present in the beta5 installation, and 'imutils' is not allowed on WCOSS2.  

It appears this situation came about from this PR [Feature 461 make compare images configurable #467](https://github.com/dtcenter/METplotpy/pull/467/files) where the line "from metcalcpy.compare_images import CompareImages" was uncommented from approximately 20 files.  CompareImages in METcalcpy [imports 'imutils'](https://github.com/dtcenter/METcalcpy/blob/57e105a42d2591a2248df3589d7869861af6cb2a/metcalcpy/compare_images.py#L29).  It looks like the PR intended to make the use of CompareImages configurable by an environment variable used in conftest.py.  But, [conftest.py](https://github.com/dtcenter/METplotpy/blob/develop/test/conftest.py) is not what is used to test on WCOSS2, instead [run_all_nco.sh](https://github.com/dtcenter/METplotpy/blob/develop/test/run_all_nco.sh) is used.  However, when running pytest the 'imutils' errors are still present.

The code was commented out again in this PR [461 revert compare images changes #472](https://github.com/dtcenter/METplotpy/pull/472).

We need a configurable option so that the CompareImages isn't imported on WCOSS2, but could be elsewhere if desired.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects###
- [x] Select **Milestone** as the next bugfix version
- [x] Select **Coordinated METplus-X.Y Support** project for support of the current coordinated release
- [x] Select **METplotpy-X.Y.Z Development** project for development toward the next official release

## Define Related Issue(s)##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next bugfix version
Select: Coordinated METplus-X.Y Support project for support of the current coordinated release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **METplotpy-X.Y.Z Development** project for development toward the next official release
- [ ] Close this issue.

**Comment by michelleharrold** [comment]
@jprestop @bikegeek @georgemccabe -- I added an account key per Julie's request (thanks, Julie!). If the work begins to take too much bandwidth/time, please check back in, so we can reassess the plan.
