### ISSUE TITLE
Include more Python packages to the conda environment

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#52]
During development, modules in the METplotpy and METcalcpy packages have required the following Python packages:
- bootstrapped
- statsmodel
- imutils
- scikit-image

- etc.

## Describe the Task ##
Perform 'conda install' for the following Python packages, to be included in the METplus conda environment:
- bootstrapped
- statsmodels
- imutils
- scikit-image
- requests
- psutil
- python-kaleido
- retrying
- yaml 
- pyyaml
- lxml
- pymysql
- plotly v 4.9 (imperative to have this version or above)
- pandas 
- numpy
- scipy
- matplotlib v 3.3 
- netcdf4
- pytest 

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] start from the original METplus conda environment that has all the Python packages for METdatadb, METplotpy, and METcalcpy
~ 2 days for the following:
- [x] perform conda install for the above 19 packages
- [x] perform a pip freeze to generate a requirements.txt
- [x perform conda env create > metplus_calc_plot.yaml 
- [x] verify that these packages can be imported (run tests in METplotpy test/ directory)
- [x] commit this to the METplotpy repo

### Relevant Deadlines ###
METcalcpy-1.0-beta deadline

### Assignee ###
- [x] Select **engineer(s)** Minna Win
- [X] **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
