### ISSUE TITLE
Create how-to documentation for line, Reliability diagram and Performance diagram plots

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#7]
## Describe the Task ##
These plots will be included in the METplotpy 1.0.0 milestone and are used by METviewer.
Include instructions on where to get sample data, how to commit and retrieve the code from the repository.  For some plots, these started out as a README file that will exist in the relevant directory.  These will need to be incorporated into online sphinx documentation.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Update documentation for performance diagram ~2-3 days
- [ ] Update documentation for line plot ~2-3 days
- [ ] Update documentation for Reliability diagram ~2-3 days
- [x] Add content to instructions for creating releases ~2-3 days (refer to METplus GitHub issue #673 for this task)

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
Split 2702691 and 2790541

### Assignee ###
- [x] Select **engineer(s)** Minna Win
- [x] Select no scientist

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests. **N/A**
- [ ] Add/update documentation. 
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
