### ISSUE TITLE
add support to reverse the connection order in ROC curve

### ISSUE THREAD

**Issue by TatianaBurek** [dtcenter/METplotpy#81]
## Describe the Enhancement ##
Add support to reverse the connection order of the points in plots generated from CTC data.
Similar functionality was added to METviewer Rscript.
https://github.com/dtcenter/METviewer/issues/246
This issue has examples of the standard plot and reversed plot

A new parameter was added to the config YAML file 'reverse_connection_order'. The default values of this parameter should be False ( use the standard order, which is reversed)

The R code that was added to the ROC R tmpl file in the METviewer repository made the following addition:
 _```
_# create the ROC point data from the components of the contingency tables
      if(reverseConnectionOrder){
        dfROC = dfPerm[order(dfPerm$fcst_thresh),];
      }else{
        dfROC = dfPerm[rev(order(dfPerm$fcst_thresh)),];_
```_

### Time Estimate ###

*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add reverse_connection_order to default yaml config file. <1 day*
- [ ] *Add support for reading in the reverse_connection_order setting <1 day*
- [ ] *For ctc data, the fcst_thresh is a combination of the operator (<,<=,==, >=, >) and numerical value, separate these and sort points based on threshold value ~1-2 days *
- [ ]  *create unit test on sorting logic* < 1 day

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2790541

## Define the Metadata ##

### Assignee ###
- [x] Select **engineer(s)** Minna
- [x] Select **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
Code that supports this behavior is in the feature_11_ROC_diagram feature branch.  Closing this issue.
