### ISSUE TITLE
Add Value-Based Difficulty Index Test

### ISSUE THREAD

**Issue by lindsayrblank** [dtcenter/METplotpy#93]
## Describe the Task ##
The difficulty index is currently tested through an image comparison. The images must be identical to pass the test. Minna discovered that the default font for matplotlib changes slightly with versions and thus causes the image comparison test to fail. I will add a test that compares expected and given values in order to test accuracy without being affected by matplotlib version changes. This will look very similar to the METcalcpy difficulty index test. 

### Time Estimate ###
Half a day to a day 

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Generate expected outcome values 
- [x] Have test script generate values
- [ ] Compare the two

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2700021

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: None
- [X] Select **scientist(s)** or **no scientist** required: Lindsay Blank

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [X] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
