### ISSUE TITLE
Fix tests for contributed plots

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METplotpy#94]
## Describe the Task ##
*Verify and fix if needed, the tests that are in the METplotpy/test directory for **contributed plots** for future regression testing.*

### Time Estimate ###

*~1 day to get broken tests working in a regression environment.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ]  Grid to Grid* _see comments below for issues with this test_ (David)
- [ ] Series Analysis _see comments below for issues with this test_ (Minna)

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)**All who provided contributed plots
- [x] Select **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by bikegeek** [comment]
### **Grid to Grid**
- test_expected_files_created() fails
- changed the import statement to: import contributed.grid_to_grid.plot_grid_to_grid as pgg (in feature_73_METplotpy_tests feature branch
- test_expected_filesizes() passes

**Comment by bikegeek** [comment]
### **Series Analysis**
**Tests that Pass:**

- test_plot_series_by_init

**Tests that Fail:**

- test_plot_series_by_lead_all.py has assertion errors.  It also looks like tests are using input and output that reside in /d1/METplus_Plotting_Data.  The data needs to be moved to 'kiowa' under /d1/projects/METplotpy/METplotpy_Data/series_analysis and/or made available 'locally' in the source code (only if data files are very small).

**Modifications:**
- ModuleNotFoundError: plot_series_by_init -> modified import to use sys.path.append to implicitly point to the METplotpy/metplotpy/contributed folder

- ModuleNotFoundError: plot_series_by_lead_all -> modified import to use sys.path.append to implicitly point to the METplotpy/metplotpy/contributed folder


Update 4/19/2021:
======
data that was on kiowa /d1/projects/METplus/METplus_Plotting_Data/series_by_init (and series_by_lead, series_by_grouping) is gone.  Re-create data that can be used for running the test and save this in the /d1/projects/METplus/METplus_Plotting_Data directory which will someday be part of the release tarball.

**Comment by bikegeek** [comment]
Done in 1.0.0
